version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: tasks-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper_hw:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper_hw
    container_name: zookeeper_hw
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000

  broker_hw:
    image: confluentinc/cp-kafka:6.2.1
    hostname: broker_hw
    container_name: broker_hw
    depends_on:
      - zookeeper_hw
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper_hw:2182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_hw:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-uitool-provectus
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker_hw:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper_hw:2182
      KAFKA_CLUSTERS_0_JMXPORT: 9997
    depends_on:
      - broker_hw
      - zookeeper_hw

volumes:
  postgres-data:
